name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Select job to run'
        required: true
        default: 'build-test'
        type: choice
        options:
          - build-test
          - release

jobs:
  build-test:
    if: ${{ github.event.inputs.job == 'build-test' }}
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build Docker image
        run: docker buildx build --tag itdogsoftware/puppeteer-e2e:${{ github.sha }} --load .

  release:
    if: ${{ github.event.inputs.job == 'release' }}
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build and push Docker image
        run: |
          docker buildx build --tag itdogsoftware/puppeteer-e2e:${{ github.ref_name }} --tag itdogsoftware/puppeteer-e2e:latest --push .
